CoSpaceFunctions.hpp
_USE_MATH_DEFINES
DLL_EXPORT
DISABLE_C4996
ENABLE_C4996
volatile int* INPUT
Referenced by SetDataAI, Setup.
volatile int* OUTPUT
Referenced by GetCommand, Setup.
char AI_MyID[2][2]
int Duration
Referenced by GetDebugInfo.
int SuperDuration
Referenced by GetDebugInfo.
int bGameEnd
Referenced by GetDebugInfo, IsGameEnd, SetGameID.
int CurAction
Referenced by GetCurAction, GetDebugInfo.
int CurGame
Referenced by GetDebugInfo, GetGameID, OnTimer, SetGameID.
int SuperObj_Num
Referenced by GetDebugInfo, GetSuperObj, SetSuperObj, Setup.
int SuperObj_X
Referenced by GetDebugInfo, GetSuperObj, SetSuperObj, Setup.
int SuperObj_Y
Referenced by GetDebugInfo, GetSuperObj, SetSuperObj, Setup.
int Teleport
Referenced by GetDebugInfo, GetTeleport.
int LoadedObjects
Referenced by GetDebugInfo.
int US_Front
Referenced by GetDebugInfo.
int US_Left
Referenced by GetDebugInfo.
int US_Right
Referenced by GetDebugInfo.
int CSLeft_R
Referenced by GetDebugInfo.
int CSLeft_G
Referenced by GetDebugInfo.
int CSLeft_B
Referenced by GetDebugInfo.
int CSRight_R
Referenced by GetDebugInfo.
int CSRight_G
Referenced by GetDebugInfo.
int CSRight_B
Referenced by GetDebugInfo.
int PositionX
Referenced by DebugWindow::GameDebug, GetDebugInfo.
int PositionY
Referenced by DebugWindow::GameDebug, GetDebugInfo.
int TM_State
Referenced by GetDebugInfo.
int Compass
Referenced by GetDebugInfo.
int Time
Referenced by GetDebugInfo, Robot::updateLoop.
int WheelLeft
Referenced by GetCommand, GetDebugInfo.
int WheelRight
Referenced by GetCommand, GetDebugInfo.
int LED_1
Referenced by GetCommand, GetDebugInfo.
int MyState
Referenced by GetCommand, GetDebugInfo.
unsigned int cycle
Referenced by OnTimer.
int AI_SensorNum
int OtherRob_PositionX
int OtherRob_PositionY
int ObjState
int ObjPositionX
int ObjPositionY
int ObjDuration
void Game0()
References Bot, debugWindow, Robot::game0Loop, DebugWindow::updateLoop.
Referenced by OnTimer, Setup.
void Game1()
References Bot, debugWindow, Robot::game1Loop, Robot::updateLoop, DebugWindow::updateLoop.
Referenced by OnTimer, Setup.
void Setup()
References Bot, debugWindow, GAME0, Game0, GAME0COLLECTIBLES, GAME0DEPOSITS, GAME0SWAMPNODES, GAME0SWAMPS, GAME0TRAPNODES, GAME0TRAPS, GAME0WALLNODES, GAME0WALLS, GAME0WATERS, GAME1, Game1, GAME1COLLECTIBLES, GAME1DEPOSITS, GAME1SWAMPNODES, GAME1SWAMPS, GAME1TRAPNODES, GAME1TRAPS, GAME1WALLNODES, GAME1WALLS, GAME1WATERS, INPUT, OUTPUT, DebugWindow::startDebugging, SuperObj_Num, SuperObj_X, SuperObj_Y.
Referenced by OnTimer.
DLL_EXPORT void SetGameID(int GameID)
References bGameEnd, CurGame.
DLL_EXPORT int GetGameID()
References CurGame.
DLL_EXPORT int IsGameEnd()
References bGameEnd.
DLL_EXPORT char* GetDebugInfo()
References bGameEnd, Compass, CSLeft_B, CSLeft_G, CSLeft_R, CSRight_B, CSRight_G, CSRight_R, CurAction, CurGame, Duration, LED_1, LoadedObjects, MyState, PositionX, PositionY, SuperDuration, SuperObj_Num, SuperObj_X, SuperObj_Y, Teleport, Time, TM_State, US_Front, US_Left, US_Right, WheelLeft, WheelRight.
DLL_EXPORT char* GetTeamName()
DLL_EXPORT int GetCurAction()
References CurAction.
DLL_EXPORT int GetTeleport()
References Teleport.
DLL_EXPORT void SetSuperObj(int X, int Y, int num)
References SuperObj_Num, SuperObj_X, SuperObj_Y.
DLL_EXPORT void GetSuperObj(int *X, int *Y, int *num)
References SuperObj_Num, SuperObj_X, SuperObj_Y.
DLL_EXPORT void SetDataAI(volatile int *packet, volatile int *AI_IN)
References INPUT.
DLL_EXPORT void GetCommand(int *AI_OUT)
References LED_1, MyState, OUTPUT, WheelLeft, WheelRight.
DLL_EXPORT void OnTimer()
References CurGame, cycle, Game0, Game1, Setup.