ColorRecognition.cpp
bool isRed(HSLColor c)
References HSLColor::h, isInRange, HSLColor::l, HSLColor::s.
Referenced by Robot::collect, isColor, Robot::shouldCollect.
bool isCyan(HSLColor c)
References HSLColor::h, isInRange, HSLColor::l, HSLColor::s.
Referenced by Robot::collect, isColor, Robot::shouldCollect.
bool isBlack(HSLColor c)
References HSLColor::l.
Referenced by Robot::collect, isColor, Robot::shouldCollect.
bool isYellow(HSLColor c)
References HSLColor::h, isInRange, HSLColor::l, HSLColor::s.
Referenced by Robot::game0Loop, Robot::game1Loop.
bool isOrange(HSLColor c)
References HSLColor::h, isInRange, HSLColor::l, HSLColor::s.
Referenced by Robot::game0Loop, Robot::game1Loop, Robot::shouldTeleport.
bool isSwamp(HSLColor c)
References HSLColor::h, isInRange, HSLColor::l, HSLColor::s.
Referenced by Robot::getVelocity.
bool isSuperObj(HSLColor c)
References HSLColor::h, isInRange, HSLColor::l, HSLColor::s.
Referenced by Robot::collect, isColor, Robot::shouldCollect.
bool isColor(HSLColor c)
References isBlack, isCyan, isRed, isSuperObj.
float rgb2h(RGBColor c)
References RGBColor::b, RGBColor::g, RGBColor::r.
float rgb2s(RGBColor c)
References RGBColor::b, RGBColor::g, RGBColor::r.
float rgb2l(RGBColor c)
References RGBColor::b, RGBColor::g, RGBColor::r.
HSLColor rgb2hsl(RGBColor rgb)
References RGBColor::b, RGBColor::g, HSLColor::h, HSLColor::l, RGBColor::r, HSLColor::s.