ColorRecognition.hpp
bool isRed(HSLColor c)
References HSLColor::h, isInRange, HSLColor::l, HSLColor::s.
Referenced by Robot::collect, isColor, Robot::shouldCollect.
bool isCyan(HSLColor c)
References HSLColor::h, isInRange, HSLColor::l, HSLColor::s.
Referenced by Robot::collect, isColor, Robot::shouldCollect.
bool isBlack(HSLColor c)
References HSLColor::l.
Referenced by Robot::collect, isColor, Robot::shouldCollect.
bool isYellow(HSLColor c)
References HSLColor::h, isInRange, HSLColor::l, HSLColor::s.
Referenced by Robot::game0Loop, Robot::game1Loop.
bool isOrange(HSLColor c)
References HSLColor::h, isInRange, HSLColor::l, HSLColor::s.
Referenced by Robot::game0Loop, Robot::game1Loop, Robot::shouldTeleport.
bool isSwamp(HSLColor c)
References HSLColor::h, isInRange, HSLColor::l, HSLColor::s.
Referenced by Robot::getVelocity.
bool isColor(HSLColor c)
References isBlack, isCyan, isRed, isSuperObj.
bool isSuperObj(HSLColor c)
References HSLColor::h, isInRange, HSLColor::l, HSLColor::s.
Referenced by Robot::collect, isColor, Robot::shouldCollect.
float rgb2h(HSLColor c)
float rgb2s(HSLColor c)
float rgb2l(HSLColor c)
HSLColor rgb2hsl(RGBColor color)
References RGBColor::b, RGBColor::g, HSLColor::h, HSLColor::l, RGBColor::r, HSLColor::s.