CommonFunctions.cpp
_USE_MATH_DEFINES
double toRadians(double d)
Referenced by Robot::getVelocity, Collectible::isCorrectCollectible.
double toDegrees(double r)
Referenced by Robot::moveToPosition.
double reverseAngle(double angle)
bool isInRange(double value, double min, double max)
Referenced by isCyan, isOrange, isRed, isSuperObj, isSwamp, isYellow.
double map(double Mmin, double Mmax, double Imin, double Imax, double input)
Referenced by DebugWindow::GameDebug, DebugWindow::startDebugging.
std::string str(T1 x, T2 y)