DebugWindow
sf::Font DebugWindow::Font
Referenced by DebugWindow, GameDebug.
Robot* DebugWindow::Bot
Referenced by GameDebug.
std::vector<unsigned int> DebugWindow::IDs
Referenced by startDebugging, stopDebugging, updateLoop.
std::vector<Field *> DebugWindow::maps
Referenced by GameDebug, startDebugging, stopDebugging.
std::vector<std::thread> DebugWindow::runningLoops
Referenced by startDebugging, stopDebugging.
std::vector<sf::RenderWindow *> DebugWindow::runningWindows
Referenced by GameDebug, stopDebugging.
std::vector<bool> DebugWindow::isRunning
Referenced by GameDebug, startDebugging, stopDebugging, updateLoop.
DebugWindow::DebugWindow()=delete
DebugWindow::DebugWindow(Robot *robot)
References Font.
void DebugWindow::updateLoop()
References IDs, isRunning, stopDebugging.
Referenced by Game0, Game1.
void DebugWindow::startDebugging(Field *map)
References GameDebug, IDs, isRunning, map, maps, runningLoops.
Referenced by Setup.
void DebugWindow::stopDebugging(unsigned int ID)
References IDs, isRunning, maps, runningLoops, runningWindows.
Referenced by updateLoop.
void DebugWindow::GameDebug(unsigned int mapIndex)
References Bot, Robot::completePath, Font, isRunning, map, Pathfinder::map, maps, Robot::pathfinder1T, Path::points, PositionX, PositionY, runningWindows, PVector::x, PVector::y.
Referenced by startDebugging.