Robot
typedef std::chrono::steady_clock Robot::Timer
volatile int* Robot::AI_IN
volatile int * Robot::AI_OUT
std::array<int *, 3> Robot::SUPER_OBJECT_INFO
PVector Robot::simPos
int Robot::compass
PVector Robot::superObject
int Robot::superObjectNum
HSLColor Robot::leftColor
HSLColor Robot::rightColor
std::array<int, 3> Robot::ultraSonic
int Robot::gameTime
int Robot::wheelLeft
int Robot::wheelRight
int Robot::led
int Robot::tp
unsigned short Robot::level
Referenced by getPointPath, teleport, updateLoop.
PVector Robot::pos
Referenced by avoidVoid, game1Loop, getPointPath, moveAlongPath, moveToPosition, updatePos.
PVector Robot::lastPos
Referenced by updateLoop, updatePos.
std::vector<Path> Robot::completePath
Referenced by game1Loop, DebugWindow::GameDebug.
Field* Robot::map0
Referenced by getPointPath.
Field * Robot::map1
Referenced by game1Loop, getPointPath, updateLoop.
Pathfinder Robot::pathfinder0
Pathfinder Robot::pathfinder1
Referenced by game1Loop.
Pathfinder Robot::pathfinder0T
Pathfinder Robot::pathfinder1T
Referenced by game1Loop, DebugWindow::GameDebug.
ObjectLoad Robot::loadedObjects
Referenced by deposit, game0Loop, game1Loop, getPointPath, shouldCollect, shouldDeposit, shouldTeleport, teleport.
unsigned int Robot::lastRGBBonus
Referenced by deposit, updateLoop.
bool Robot::huntingSuperObj
Referenced by getDesiredLoad, updateLoop.
std::vector<Collectible *> Robot::superObjects
Referenced by game1Loop, getDesiredLoad, getPointPath, updateLoop.
int Robot::remainingMapTime
Referenced by game1Loop, getDesiredLoad, shouldDeposit, shouldTeleport, updateLoop.
std::chrono::time_point<Timer> Robot::lastProgramCycle
Referenced by game1Loop, updateLoop.
std::chrono::time_point<Timer> Robot::depositingSince
Referenced by deposit, shouldDeposit.
std::chrono::time_point<Timer> Robot::collectingSince
Referenced by collect, shouldCollect.
std::chrono::time_point<Timer> Robot::lastPositionUpdate
Referenced by updatePos.
bool Robot::setIN(volatile int *IN)
bool Robot::setOUT(volatile int *OUT)
void Robot::updateSimVars()
Robot::Robot(volatile int *IN, volatile int *OUT, std::array< int *, 3 > superObject, Field *map0, Field *map1)
void Robot::wheels(int l, int r)
controls the robots wheels
Referenced by collect, deposit, game0Loop, game1Loop, moveToPosition.
void Robot::moveAlongPath(Path &path)
References Path::getClosestNormalPoint, moveToPosition, pos.
Referenced by game1Loop.
PVector Robot::updatePos()
updates the position of the robot mathematically and returns the change
References geometry::dist, getVelocity, lastPos, lastPositionUpdate, pos, RPOS_ERROR_MARGIN.
Referenced by updateLoop.
int Robot::moveToPosition(PVector p)
References checkUsSensors, geometry::dist, pos, toDegrees, geometry::vector2Angle, wheels.
Referenced by moveAlongPath.
int Robot::checkUsSensors(int l, int f, int r)
checks if l, f or r is higher than the us-sensor values. returns a binary-encoded value
Referenced by game0Loop, moveToPosition.
void Robot::updateLoop()
References Field::addCollectible, ERROR_MESSAGE, GAME0_TIME, GAME1_TIME, huntingSuperObj, lastPos, lastProgramCycle, lastRGBBonus, level, map1, remainingMapTime, PVector::set, superObjects, Time, updatePos.
Referenced by Game1.
void Robot::game0Loop()
game loop for first map
References checkUsSensors, deposit, isOrange, isYellow, loadedObjects, ObjectLoad::num, shouldCollect, shouldDeposit, shouldTeleport, teleport, wheels.
Referenced by Game0.
void Robot::game1Loop()
game loop for second map
References ObjectLoad::addObject, Pathfinder::AStar, avoidVoid, collect, completePath, deposit, geometry::dist, ERROR_MESSAGE, Field::getCollectible, Field::getDeposits, getDesiredLoad, getPointPath, Path::isEmpty, isOrange, isYellow, lastProgramCycle, Path::length, loadedObjects, map1, moveAlongPath, ObjectLoad::num, pathfinder1, pathfinder1T, pos, remainingMapTime, shouldCollect, shouldDeposit, Collectible::state, superObjects, Collectible::visited, wheels.
Referenced by Game1.
PVector Robot::getVelocity(long long int dt) const
gets the current velocity for a certain change in time (in ms)
References geometry::angle2Vector, isSwamp, ROBOT_AXLE_LENGTH, ROBOT_SPEED, PVector::rotate, SWAMP_SPEED_PENALITY, toRadians.
Referenced by updatePos.
bool Robot::shouldCollect()
decides whether collecting a point is a good idea or not
References ObjectLoad::black, collectingSince, ObjectLoad::cyan, getDesiredLoad, isBlack, isCyan, isRed, isSuperObj, loadedObjects, ObjectLoad::num, ObjectLoad::red, ObjectLoad::super.
Referenced by game0Loop, game1Loop.
int Robot::collect()
collects a point
References collectingSince, isBlack, isCyan, isRed, isSuperObj, wheels.
Referenced by game1Loop.
bool Robot::shouldDeposit()
decides whether depositing is a good idea or not
References depositingSince, ObjectLoad::getValue, loadedObjects, ObjectLoad::num, remainingMapTime.
Referenced by game0Loop, game1Loop, shouldTeleport.
void Robot::deposit()
deposits
References ObjectLoad::clearLoad, depositingSince, lastRGBBonus, loadedObjects, ObjectLoad::rgb, wheels.
Referenced by game0Loop, game1Loop.
bool Robot::shouldTeleport()
decides whether teleporting is a good idea or not
References isOrange, loadedObjects, ObjectLoad::num, remainingMapTime, shouldDeposit.
Referenced by game0Loop.
void Robot::teleport()
teleports
References ObjectLoad::clearLoad, level, loadedObjects.
Referenced by game0Loop.
int Robot::avoidVoid() const
returns a turning direction if the robot is about to drive off map
References pos, PVector::x, PVector::y.
Referenced by game1Loop.
std::array< int, 4 > Robot::getDesiredLoad() const
References huntingSuperObj, remainingMapTime, superObjects.
Referenced by game1Loop, shouldCollect.
std::vector< PVector > Robot::getPointPath(std::array< int, 4 > desiredLoad)
References ObjectLoad::all, geometry::dist, Field::getCollectibles, level, loadedObjects, map0, map1, ObjectLoad::num, pos, superObjects.
Referenced by game1Loop.