Field
std::vector<Area> Field::Walls_
Contains all walls.
std::vector<Area> Field::Traps_
Contains all traps.
std::vector<Area> Field::Swamps_
Contains all swamps.
std::vector<Area> Field::Waters_
Contains all waters / bonus areas.
std::vector<PVector> Field::Deposits_
The deposits saved as points in their respective center.
std::vector<PVector> Field::WallNodes_
Contains all wall nodes.
std::vector<PVector> Field::TrapNodes_
Contains all trap nodes.
std::vector<PVector> Field::SwampNodes_
Contains all trap nodes.
std::array<std::vector<Collectible>, 4> Field::Collectibles_
contains collectibles of all colors They're ordered the following: index = 0 <=> Red; 1 <=> Cyan/Green; 2 <=> Black; 3 <=> SuperObject
PVector Field::size_
represents the size in cm of the field object There can never be a negative sized Field. The size is also defined by the CoSpace-Rules so FieldA = {270, 180}; FieldB = {360, 270})
Field::Field(const int &width, const int &height, const std::vector< Area > &walls, const std::vector< Area > &traps, const std::vector< Area > &swamps, const std::vector< Area > &waters, const std::vector< PVector > &deposits, const std::vector< PVector > &wallNodes, const std::vector< PVector > &trapNodes, const std::vector< PVector > &swampNodes, const std::vector< Collectible > &collectibles)
MapData
Collectible * Field::addCollectible(Collectible collectible)
References Collectible::color.
Referenced by Robot::updateLoop.
bool Field::removeCollectible(Collectible collectible)
References Collectible::color.
Collectible * Field::getCollectible(PVector pos, double angle, double uncertainty, int color)
References ERROR_MESSAGE, getCollectibles.
Referenced by Robot::game1Loop.
PVector Field::getSize()
Getter for the size.
std::vector< Area > Field::getMapObjects(const std::vector< unsigned int > &indices)
gets map objects based on their index indices the index of the wanted map objects 0 -> walls; 1 -> traps; 2 -> swamps; 3 -> bonus areas; a vector containing all map object areas with the indices
References ERROR_MESSAGE.
Referenced by Pathfinder::AStar, Node::calculateCost, Pathfinder::Pathfinder.
std::vector< PVector > Field::getMapNodes(const std::vector< unsigned int > &indices)
gets map nodes based on their index indices 0 -> walls; 1 -> traps; 2 -> swamps a vector containing all map object areas with the indices
References ERROR_MESSAGE.
Referenced by Pathfinder::Pathfinder.
std::vector< PVector > Field::getDeposits()
Getter method for deposits.
Getter for field::collectibles
Referenced by Robot::game1Loop.
std::vector< Collectible > Field::getCollectibles(const std::vector< unsigned int > &colors)
Getter method for collectibles.
Getter for field::collectibles
References ERROR_MESSAGE.
Referenced by getCollectible, Robot::getPointPath.