Node
bool Node::isClosed
Booleans that indicate if this Node is in a special list used by the A*Pathfinding algorithm These variables aren't updated automatically
Referenced by Pathfinder::AStar.
bool Node::isOpen
Referenced by Pathfinder::AStar.
double Node::g
Doubles that are used in the A*Pathfinding algorithm These variables aren't updated automatically
Referenced by Pathfinder::AStar.
double Node::f
Node* Node::previous
A pointer to the last visited Node. This is used by the A*Pathfinding algorithm This variable isn't updated automatically
PVector Node::pos
A PVector struct that stores the position of this node This variable could be constant and is not meant to change. However for usability reasons it's not constant.
Referenced by Pathfinder::AStar, calculateCost, canSee.
Field* Node::field
A pointer to the field Object this Node is stored in This pointer can be used to find neighbours or obstacles. It is important that a node knows in which field it is operating in. This variable could be constant and is not meant to change. However for usability reasons it's not constant.
Referenced by calculateCost.
std::vector<std::pair<Node *, double> > Node::neighbours
A vector that stores all visible neighbour nodes with their respective costs. To optimise speed the A*Pathfinding works on a precalculated environment. This vector keeps track of neighbours and distances/costs.
Referenced by addNeighbour, Pathfinder::AStar, findNeighbours, removeNeighbour.
Node::Node(PVector _pos, Field *_field)
Node
References ERROR_MESSAGE.
double Node::calculateCost(const Node &node)
This Method calculates a cost to a Node node This function takes visibility into account(for that it uses Node::canSee()). If this Node can't see the other Node the cost will be -1. Other wise the cost is calculated also taking swamps into account.
References geometry::dist, field, Field::getMapObjects, geometry::intersection, geometry::isInside, pos, SWAMP_SPEED_PENALITY.
Referenced by Pathfinder::AStar, findNeighbours.
bool Node::canSee(const Node &node, const std::vector< Area > &ObstaclesStructs) const
This Method checks if this Node can see a certain other Node node ObstaclesStructs A vector containing all structures that are counted as Obstacles
References geometry::isIntersecting, pos.
Referenced by findNeighbours.
int Node::findNeighbours(std::vector< Node > &Nodes, const std::vector< Area > &ObstacleStructs)
This Method gets every neighbour and calculates the cost. Nodes A vector of pointers to Nodes ObstaclesStructs A vector containing all structures that are counted as Obstacles the number of existing neighbours Every Node in Nodes has to be initialized before executing this Method
References calculateCost, canSee, neighbours.
Referenced by Pathfinder::AStar.
void Node::addNeighbour(Node *neighbour, const double &cost)
Adds a neighbour and it's cost To increase the speed this method will not calculate the cost. This has to be done via "calculateCost()" and then funneled in as a parameter to this function
References neighbours.
bool Node::removeNeighbour(Node *neighbour)
Removes a neighbour This function only removes one neighbour by iterating over "neighbours" and exiting as soon as one element has been found
References neighbours.