ObjectLoad
std::array<std::vector<Collectible *>, 4> ObjectLoad::m_loadedCollectibles
unsigned int ObjectLoad::m_count
ObjectLoad::ObjectLoad()
ObjectLoad::ObjectLoad(const std::vector< Collectible * > &collectibles)
void ObjectLoad::addObject(Collectible *collectible)
Referenced by Robot::game1Loop, setLoad.
bool ObjectLoad::removeObject(Collectible *collectible)
References Collectible::color.
void ObjectLoad::setLoad(const std::vector< Collectible * > &collectible)
References addObject.
void ObjectLoad::clearLoad()
Referenced by Robot::deposit, Robot::teleport.
unsigned int ObjectLoad::getValue()
References black, cyan, red, rgb, super.
Referenced by Robot::shouldDeposit.
unsigned int ObjectLoad::rgb()
References black, cyan, red.
Referenced by Robot::deposit, getValue.
unsigned int ObjectLoad::red()
Referenced by all, getValue, rgb, Robot::shouldCollect.
unsigned int ObjectLoad::cyan()
Referenced by all, getValue, rgb, Robot::shouldCollect.
unsigned int ObjectLoad::black()
Referenced by all, getValue, rgb, Robot::shouldCollect.
unsigned int ObjectLoad::super()
Referenced by all, getValue, Robot::shouldCollect.
std::array< unsigned int, 4 > ObjectLoad::all()
References black, cyan, red, super.
Referenced by Robot::getPointPath.
const std::array< std::vector< Collectible * >, 4 > & ObjectLoad::loadedObjects()
unsigned int ObjectLoad::num() const
Referenced by Robot::game0Loop, Robot::game1Loop, Robot::getPointPath, Robot::shouldCollect, Robot::shouldDeposit, Robot::shouldTeleport.