PVector
double PVector::x
the x-Position of the PVector
Referenced by Area::Area, Robot::avoidVoid, geometry::dot, DebugWindow::GameDebug, getMag, geometry::getNormalPoint, geometry::intersection, geometry::isLeft, Path::isOnPath, normalize, operator!=, operator*=, operator+=, operator-=, operator/=, operator==, rotate, round, set, setMag, geometry::sqDist, str, geometry::vector2Angle.
double PVector::y
the x-Position of the PVector
Referenced by Area::Area, Robot::avoidVoid, geometry::dot, DebugWindow::GameDebug, getMag, geometry::getNormalPoint, geometry::intersection, geometry::isInside, geometry::isLeft, Path::isOnPath, normalize, operator!=, operator*=, operator+=, operator-=, operator/=, operator==, rotate, round, set, setMag, geometry::sqDist, str, geometry::vector2Angle.
PVector::PVector()
creates a 2D Point-Vector at (NAN | NAN)
Referenced by operator*, operator+, operator-, operator/.
PVector::PVector(double _x, double _y)
creates a 2D Point-Vector at the given coordinates _x x-Position of the PVector. _y y-Position of the PVector.
PVector PVector::set(double _x, double _y)
sets the position to the given coordinates _x new x-Position of the PVector. _y new y-Position of the PVector. a copy of itself after executing the method
References x, y.
Referenced by normalize, rotate, round, setMag, Robot::updateLoop.
PVector PVector::normalize()
normalizes the PVector's magnitude a copy of itself after executing the method
References getMag, set, x, y.
Referenced by setMag.
double PVector::getMag() const
calculates and returns the magnitude of the PVector magnitude of the PVector
References x, y.
Referenced by normalize.
PVector PVector::setMag(double mag)
sets the magnitude of the PVector mag the new magnitude the PVector should have a copy of itself after executing the method
References normalize, set, x, y.
Referenced by geometry::getNormalPoint.
PVector PVector::rotate(double angle)
counter-clockwise rotation
rotates the PVector counter-clockwise by a given angle angle the angle the PVector should be rotated by angle must be in radians a copy of pVector after executing the method
References set, x, y.
Referenced by Path::getClosestNormalPoint, Robot::getVelocity.
PVector PVector::round()
rounds the coordinates of the PVector a copy this PVector after executing the method
References set, x, y.
bool PVector::operator==(const PVector &lhs) const
binary operator to compare two pVectors with each other for equal coordinates lhs the other PVector that should be compared to this true if both the x and the y coordinate of each PVector match
References x, y.
bool PVector::operator==(const double &d) const
binary operator to compare this PVector with a double for unequal coordinates lhs the other PVector that should be compared to this true if either the x or the y coordinate doesn't match
References x, y.
bool PVector::operator!=(const PVector &lhs) const
binary operator to compare a pVectors with a double for unequal coordinates d the double that should be compared to this true if either the x or the y coordinate of this PVector doesn't match with d
References x, y.
bool PVector::operator!=(const double &lhs) const
binary operator to compare this PVector with a double for equal coordinates d the double that should be compared to this true if both the x and the y coordinate of this PVector match with d
References x, y.
PVector & PVector::operator+=(const PVector &rhs)
References x, y.
PVector PVector::operator+(const PVector &rhs)
References PVector.
PVector & PVector::operator-=(const PVector &rhs)
References x, y.
PVector PVector::operator-(const PVector &rhs)
References PVector.
PVector & PVector::operator*=(const double &m)
References x, y.
PVector PVector::operator*(const double &m)
References PVector.
PVector & PVector::operator/=(const double &m)
References x, y.
PVector PVector::operator/(const double &m)
References PVector.
PVector::operator bool() const
binary operator to check whether a PVectors position is defined or not true if both the x and the y coordinate are not NAN
std::string PVector::str() const
References x, y.
Referenced by Line::str.
PVector PVector::setMag(PVector &pVector, double mag)
sets the magnitude of a given PVector pVector the PVector the magnitude should be changed of mag the new magnitude pVector should have this is the static version of PVector::setMag(); a copy of pVector after executing the method
References normalize, x, y.
PVector PVector::round(const PVector &pVector)
rounds the coordinates of a given pVector pVector the PVector the coordinates should be rounded of this is the static version of PVector::round(); a copy of pVector after executing the method
References x, y.
std::string PVector::str(PVector pVector)
References x, y.