Path
std::vector<PVector> Path::points
Contains all points of the path in order so that p[0] -> p[1] -> p[2] represents the path.
Referenced by addPoint, DebugWindow::GameDebug, getClosestNormalPoint, getLast, isEmpty, isOnPath, length, removeLast, size.
double Path::r
The radius of the Path.
Referenced by isOnPath.
Path::Path(std::vector< PVector > points, double _r)
Path
PVector Path::getClosestNormalPoint(PVector p, double d)
Calculates the closest normal point to a point that is extended by the factor d p a point the normal should be calculated to d the amount by which the point should lie ahead on the path. This method calculates a point that lies on the path or an extension of one of it's lines. This point is moved by the factor d on the path. (If d = 0 than the point is just a normal point to p)
References geometry::dist, geometry::getNormalPoint, geometry::isLeft, points, PVector::rotate.
Referenced by Robot::moveAlongPath.
bool Path::isOnPath(PVector p)
Checks whether a point is inside the radius of the path.
References geometry::dist, points, r, PVector::x, PVector::y.
void Path::addPoint(PVector p)
Adds a point to the Path.
References points.
void Path::removeLast()
Removes the last point of the path.
References points.
PVector Path::getLast()
Returns the last point of the path.
References points.
bool Path::isEmpty() const
Checks whether the Path is empty.
References points.
Referenced by Robot::game1Loop.
unsigned int Path::size() const
Returns the size of the Path vector.
References points.
double Path::length()
References geometry::dist, points.
Referenced by Robot::game1Loop.