main.cpp
CsBot_AI_H
CsBot_AI_C
DebugWindow* debugWindow
Referenced by Game0, Game1, Setup.
Field* GAME0
Referenced by Setup.
Field* GAME1
Referenced by Setup.
Robot* Bot
Referenced by Game0, Game1, Setup.
void Setup()
References Bot, debugWindow, GAME0, Game0, GAME0COLLECTIBLES, GAME0DEPOSITS, GAME0SWAMPNODES, GAME0SWAMPS, GAME0TRAPNODES, GAME0TRAPS, GAME0WALLNODES, GAME0WALLS, GAME0WATERS, GAME1, Game1, GAME1COLLECTIBLES, GAME1DEPOSITS, GAME1SWAMPNODES, GAME1SWAMPS, GAME1TRAPNODES, GAME1TRAPS, GAME1WALLNODES, GAME1WALLS, GAME1WATERS, INPUT, OUTPUT, DebugWindow::startDebugging, SuperObj_Num, SuperObj_X, SuperObj_Y.
Referenced by OnTimer.
void Game0()
References Bot, debugWindow, Robot::game0Loop, DebugWindow::updateLoop.
Referenced by OnTimer, Setup.
void Game1()
References Bot, debugWindow, Robot::game1Loop, Robot::updateLoop, DebugWindow::updateLoop.
Referenced by OnTimer, Setup.