geometry
bool geometry::isLeft(PVector p0, PVector p1, PVector p2)
geometry
References PVector::x, PVector::y.
Referenced by Path::getClosestNormalPoint, isInside.
bool geometry::isInside(const PVector &p, Area &area)
checks if a point lies inside the Area p A point true if point lies inside of the Area. Otherwise false
References Area::getCorners, isLeft, PVector::y.
Referenced by Node::calculateCost.
PVector geometry::intersection(Line &l1, Line &l2)
calculates an intersection point between two lines l1 a line l2 another line intersection point if existing. Otherwise (-1, -1)
References Line::p1, Line::p2, PVector::x, PVector::y.
Referenced by Node::calculateCost, isIntersecting.
bool geometry::isIntersecting(Line &l1, Line &l2)
References intersection.
Referenced by Node::canSee, isIntersecting.
bool geometry::isIntersecting(Line l1, const std::vector< Area > &Obstacles)
References isIntersecting.
double geometry::sqDist(const PVector &p1, const PVector &p2)
References PVector::x, PVector::y.
Referenced by dist.
double geometry::dist(const PVector &p1, const PVector &p2)
References sqDist.
Referenced by Node::calculateCost, Robot::game1Loop, Path::getClosestNormalPoint, Robot::getPointPath, Collectible::isCorrectCollectible, Path::isOnPath, Path::length, Robot::moveToPosition, Robot::updatePos.
double geometry::dot(PVector p1, PVector p2)
References PVector::x, PVector::y.
Referenced by getNormalPoint.
PVector geometry::getNormalPoint(Line line, PVector point)
Calculates normal point on a line to another point line The line point The point This function returns the intersection between the line and a line which goes through the point p and is orthogonal to the line This point however doesn't need to be on the line and can also lie on a extension of this line
References dot, Line::p1, Line::p2, PVector::setMag, PVector::x, PVector::y.
Referenced by Path::getClosestNormalPoint.
PVector geometry::angle2Vector(double a)
Referenced by Robot::getVelocity, Collectible::isCorrectCollectible.
double geometry::vector2Angle(PVector v)
References PVector::x, PVector::y.
Referenced by Robot::moveToPosition.
double geometry::vector2Angle(double x, double y)