#include "MapData.hpp"

//   ______            __
//  |      |.-----..--|  |.-----.
//  |   ---||  _  ||  _  ||  -__|
//  |______||_____||_____||_____|
//

/**     -----------     **/
/**                     **/
/**     Collectible     **/
/**                     **/
/**     -----------     **/

Collectible::Collectible(const PVector &p, const unsigned int &c, bool worthDouble) :
        pos(p), state(0), visited(0), isWorthDouble(worthDouble) {
    if (c <= 3) {
        color = c;
    } else {
        COLLECTIBLE_ERROR("Can't initialize Collectible with color " + std::to_string(c) + "!")
        return;
    }
}

bool Collectible::isCorrectCollectible(PVector robotPos, double angle, double uncertainty,
                                       std::vector<int> possibleStates) const {
    return (geometry::dist(robotPos + (geometry::angle2Vector((angle - COLOR_SENSOR_ANGLE_OFFSET) * M_PI / 180) *
                                       COLOR_SENSOR_DIST_TO_CORE), pos) < uncertainty
            || geometry::dist(robotPos + (geometry::angle2Vector((angle + COLOR_SENSOR_ANGLE_OFFSET) * M_PI / 180) *
                                          COLOR_SENSOR_DIST_TO_CORE), pos) < uncertainty)
           && (possibleStates.empty()
           || std::find(possibleStates.begin(), possibleStates.end(), state) != possibleStates.end());
}

bool Collectible::operator==(const Collectible &lhs) const {
    return pos == lhs.pos && color == lhs.color;
}


/**     -----------    **/
/**                    **/
/**        Field       **/
/**                    **/
/**     -----------    **/


Field::Field(const int &width, const int &height,
             const double &scaleX, const double &scaleY, const std::string &map,
             const std::vector<PVector> &deposits,
             const std::vector<Collectible> &collectibles) : width_(width), height_(height) {

    FIELD_LOG("Creating new Field-object")

    // field::deposits: Deposit Areas of the field
    Deposits_ = deposits;
    scale_ = {scaleX, scaleY};
    Map_ = map;

    // field::Collectibles: Collectible Points of the field
    for (auto collectible : collectibles) {
        if (collectible.color <= 3) {
            collectible.pos.x /= scaleX;
            collectible.pos.y /= scaleY;
            Collectibles_[collectible.color].push_back(collectible);
        } else {
            FIELD_ERROR("Can't add Collectible at: " << collectible.pos << " with color: " << collectible.color
                                                     << "\n\t -> Collectible will be skipped.")
        }
    }
}

/** Getter for field::collectibles **/
std::vector<PVector> Field::getDeposits() {
    return Deposits_;
}

/** Getter for field::collectibles **/
std::vector<Collectible *> Field::getCollectibles(const std::vector<unsigned int> &colors) {
    std::vector<Collectible *> returnVector = {};
    // return after all indices have been checked.
    for (unsigned int index : colors) {
        if (index <= 3) {
            for (Collectible &collectible : Collectibles_[index]) {
                returnVector.push_back(&collectible);
            }
        } else {
            FIELD_ERROR("index out of range");
        }
    }

    FIELD_LOG("Returning " << returnVector.size() << " collectibles")
    return returnVector;
}


void Field::spawnTempWall(PVector pos, int r) {

    tempWallTiles_.push_back({std::chrono::steady_clock::now(), {}});

    const int centerX = static_cast<int>(round(pos.x * scale_.x));
    const int centerY = static_cast<int>(round(pos.y * scale_.y));
    const int radius = static_cast<int>(round(pos.x * geometry::dist({0, 0}, scale_)));
    int index;

    for (int x = -radius + centerX; x < radius + centerX; ++x) {
        for (int y = -radius + centerY; y < radius + centerY; ++y) {

            if ((x - centerX) * (x - centerX) + (y - centerY) * (y - centerY) > r * r ||
                x < 0 || x >= width_ || y < 0 || y >= height_) {
                continue;
            }

            index = idx(x, y);

            if (Map_[index] == MAP_EMPTY_TILE) {
                tempWallTiles_.back().second.push_back(index);
                Map_.at(index) = MAP_TEMP_WALL_TILE;
            }
        }
    }

    FIELD_LOG("After spawning: " << Map_)
}


void Field::clearTempWall(double lifetime) {

    int removed = 0;
    while (!tempWallTiles_.empty()) {
        if (std::chrono::duration<double, std::milli>(
                std::chrono::steady_clock::now() - tempWallTiles_.front().first).count() >= lifetime) {
            for (auto index : tempWallTiles_.front().second) {
                Map_.at(index) = MAP_EMPTY_TILE;
            }

            tempWallTiles_.pop_front();
            removed++;
        } else {
            return;
        }
    }

    if (removed != 0) {
        FIELD_LOG("After clearing " << removed << " objects: " << Map_)
    }
}


Collectible *
Field::getCollectible(PVector robotPos, double angle, double uncertainty, int color, std::vector<int> possibleStates) {

    std::vector<Collectible *> collectibles;

    if (color == -1) {
        collectibles = getCollectibles({0, 1, 2, 3});
    } else if (color >= 0 && color <= 3) {
        collectibles = getCollectibles({static_cast<unsigned int> (color)});
    } else {
        FIELD_ERROR(color << " is an invalid color")
    }

    for (auto collectible : collectibles) {
        if (collectible->isCorrectCollectible(robotPos, angle, uncertainty, possibleStates)) {
            return collectible;
        }
    }

    FIELD_WARNING("no valid collectible found")
    return nullptr;
}

Collectible *Field::addCollectible(Collectible collectible) {
    Collectibles_[collectible.color].push_back(collectible);
    return &Collectibles_[collectible.color].back();
}

bool Field::removeCollectible(Collectible collectible) {
    auto it = std::find(Collectibles_[collectible.color].begin(), Collectibles_[collectible.color].end(), collectible);

    if (it != Collectibles_[collectible.color].end()) {
        Collectibles_[collectible.color].erase(it);
        FIELD_LOG("Successfully removed Collectible")
        return true;
    }
    FIELD_WARNING("Couldn't remove Collectible")
    return false;
}

// TODO: The pathfinding function seems to fail or delete the found path entirely.
//  Fix it so that it doesn't fail anymore
std::vector<PVector> Field::AStarFindPath(PVector start, PVector end) {

    PATHFINDER_LOG("Setting up path finder... from " << round(start.x * scale_.x) << " | " << round(start.y * scale_.y)
                                                     << " to " << round(end.x * scale_.x) << " | "
                                                     << round(end.y * scale_.y))

    auto comp = [](const std::tuple<double, int> &n1, const std::tuple<double, int> &n2) {
        return std::get<0>(n1) > std::get<0>(n2);
    };

    const int startIdx = idx(static_cast<int>(round(start.x * scale_.x)), static_cast<int>(round(start.y * scale_.y)));
    const int endIdx = idx(static_cast<int>(round(end.x * scale_.x)), static_cast<int>(round(end.y * scale_.y)));

    if (startIdx == endIdx) {
        PATHFINDER_WARNING("Start is end")
        return {end};
    }

    const int size = width_ * height_;

    if (startIdx >= size || endIdx >= size) {
        PATHFINDER_ERROR("Start or end is outside of the map!")
        return {};
    }

    std::priority_queue<std::tuple<double, int>,
            std::vector<std::tuple<double, int>>, decltype(comp)> pq(comp);
    std::vector<int> p(size); // prev
    std::vector<double> d(size, INT_MAX); // dist (filled with max distance)

    PATHFINDER_LOG("Starting path finder...")

    d[startIdx] = 0;
    pq.push(std::make_tuple(0 + heuristic(startIdx, endIdx), startIdx));

    while (!pq.empty()) {

        int u = std::get<1>(pq.top());
        pq.pop(); // Get top element

        for (auto e : {-width_ - 1, -width_ + 1, +width_ - 1, +width_ + 1, +1, -1, +width_, -width_}) {
            int v = u + e; // neighbor node
            if (((e == 1 || e == -width_ + 1 || e == width_ + 1) && (v % width_ == 0)) // x-bounds
                || ((e == -1 || e == -width_ - 1 || e == width_ - 1) && (u % width_ == 0)))
                continue;

            if (0 <= v && v < size) { // Out of bounds check
                if (d[v] > d[u] + heuristic(u, v) && Map_[v] == MAP_EMPTY_TILE) {
                    p[v] = u;
                    d[v] = d[u] + heuristic(u, v);

                    if (v == endIdx) {
                        PATHFINDER_LOG("Path finder found a path")

                        std::vector<PVector> tPath{}, path{};

                        // Traverse whole path back
                        for (int i = endIdx; i != startIdx;) {
                            PVector cur = coord(i);
                            i = p[i];
                            tPath.emplace_back(cur.x, cur.y);
                        }
                        tPath.push_back(start);


                        // shorten path to only necessary nodes
                        int i = 0, j = 0;
                        while (i < tPath.size() - 1 && j < tPath.size()) {

                            path.push_back(tPath[i]);

                            for (j = i + 1; j < tPath.size(); ++j) {

                                for (int k = i; k < j; ++k) {
                                    // Check if inbetween nodes are one a line
                                    if (geometry::distToLine(tPath[i], tPath[j], tPath[k]) > 1) {
                                        // inbetween node is not on a line, go back one and break out of the checking loop
                                        k = j;
                                        j = tPath.size();
                                    }
                                }
                            }
                        }
                        path.push_back(start);
                        PATHFINDER_LOG("Returning " << path.size() << " Nodes")
                        return path;

                    }

                    pq.push(std::make_tuple(d[v] + heuristic(v, endIdx), v));

                }
            }
        }
    }

    PATHFINDER_WARNING("Path finder couldn't find a path")
    return {};
}

int Field::idx(int x, int y) const {
    return x + y * width_;
}

double Field::heuristic(int idx1, int idx2) const {
    return sqrt(pow(idx1 % width_ - idx2 % width_, 2) + pow(idx1 / width_ - idx2 / width_, 2));
}

PVector Field::coord(int idx) const {
    return PVector(idx % width_, idx / width_);
}

PVector Field::getScale() const {
    return scale_;
}

std::string Field::getMap() {
    return Map_;
}

std::string Field::getFlippedMap() {
    std::string newMap = Map_;
    for (int j = 0; j < height_; ++j) {
        for (int i = 0; i < width_; ++i) {
            newMap.at(i + (height_ - j - 1) * width_) = Map_.at(i + j * width_);
        }
    }
    return newMap;
}

char Field::getMapAt(int x, int y) {
    return Map_.at(x + y * width_);
}

char Field::getMapAtRealPos(PVector pos) {
    return Map_.at(idx(static_cast<int>(round(pos.x * scale_.x)), static_cast<int>(round(pos.y * scale_.y))));
}


int Field::getHeight() const {
    return height_;
}

[[maybe_unused]] int Field::getWidth() {
    return width_;
}


/**     -----------     **/
/**                     **/
/**      geometry       **/
/**                     **/
/**     -----------     **/


// geometry::onSide():  Test if a point p2 is left/on/right a line through p0 and p1.
//      Input:  PVector p0, p1, p2
//      Return: >0 left; =0 on; <0 right
bool geometry::isLeft(PVector p0, PVector p1, PVector p2) {
    return (p1.x - p0.x) * (p2.y - p0.y) - (p2.x - p0.x) * (p1.y - p0.y) > 0;
}

double geometry::sqDist(double x1, double y1, double x2, double y2) {
    return pow(x1 - x2, 2) + pow(y1 - y2, 2);
}

double geometry::sqDist(const PVector &p1, const PVector &p2) {
    return pow(p1.x - p2.x, 2) + pow(p1.y - p2.y, 2);
}

double geometry::dist(const PVector &p1, const PVector &p2) {
    return sqrt(pow(p1.x - p2.x, 2) + pow(p1.y - p2.y, 2));
}

double geometry::dist(double x1, double y1, double x2, double y2) {
    return sqrt(pow(x1 - x2, 2) + pow(y1 - y2, 2));
}

PVector geometry::angle2Vector(double a) {
    return {cos(a), sin(a)};
}

double geometry::vector2Angle(double x, double y) {

    double angle = atan2(y, x);

    return (angle >= 0) ? angle : 2 * M_PI + angle;
}

double geometry::vector2Angle(PVector v) {
    return geometry::vector2Angle(v.x, v.y);
}

double geometry::dot(PVector p1, PVector p2) {
    return p1.x * p2.x + p1.y * p2.y;
}

double geometry::distToLine(double p1_x, double p1_y, double p2_x, double p2_y, double p0_x, double p0_y) {
    return fabs((p2_x - p1_x) * (p1_y - p0_y) - (p1_x - p0_x) * (p2_y - p1_y)) /
           sqrt((p2_x - p1_x) * (p2_x - p1_x) + (p2_y - p1_y) * (p2_y - p1_y));
}

double geometry::distToLine(PVector p1, PVector p2, PVector p0) {
    return distToLine(p1.x, p1.y, p2.x, p2.y, p0.x, p0.y);
}

bool geometry::isInside(PVector point, PVector min, PVector max) {
    return min.x <= point.x && point.x < max.x && min.y <= point.y && point.y < max.y;
}




///   _______                _____          __
///  |   |   |.---.-..-----.|     \ .---.-.|  |_ .---.-.
///  |       ||  _  ||  _  ||  --  ||  _  ||   _||  _  |
///  |__|_|__||___._||   __||_____/ |___._||____||___._|
///                  |__|

//------------- World1_Map --------------//

const std::vector<PVector> World1DEPOSITS = {{79,11},{15,59}};
const int World1MAP_WIDTH = 96; 
const int World1MAP_HEIGHT = 72; 
const std::string World1MAP = "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEUUUUUUUUEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEUUUUUUUUUEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEUUUUUUUUUEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEUUUUUUUUUEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEUUUUUUUUUEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEUUUUUUUUUEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEUUUUUUUUUEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEUUUUUUUUUEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEUUUUUUUUUEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEEEEEEEETTTTTTEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEEEEETTTTTTTTTTTTEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEEEETTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEEETTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEEETTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEEETTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEETTTTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEETTTTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEETTTTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEETTTTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEETTTTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEETTTTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEEETTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEEETTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEEETTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEEEETTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEEEEETTTTTTTTTTTTEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEEEEEEEETTTTTTEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEUUUUUUUUUEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEUUUUUUUUUUEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEUUUUUUUUUUEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEUUUUUUUUUUEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEUUUUUUUUUUEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEUUUUUUUUUUEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEUUUUUUUUUUEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEUUUUUUUUUUEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEUUUUUUUUUUEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE";
const std::vector<Collectible> World1COLLECTIBLES = {{{62.84,24.0},2,false},{{70.08,19.72},2,false},{{69.03,28.84},2,false},{{56.21,16.99},2,false},{{50.04,23.11},2,false},{{55.26,23.88},2,false},{{42.12,17.54},2,false},{{66.01,33.73},2,false},{{73.4,25.42},2,false},{{61.88,28.4},2,false},{{60.63,38.0},2,false},{{66.83,41.69},2,false},{{74.22,49.85},2,false},{{60.73,34.25},2,false},{{61.64,47.02},2,false},{{42.47,23.88},2,false},{{47.51,18.84},2,false},{{39.71,20.46},2,true},{{41.55,27.87},2,false},{{13.81,59.17},0,false},{{19.57,52.88},0,false},{{19.0,66.37},0,false},{{8.58,51.82},0,false},{{8.39,64.01},0,false},{{19.54,59.05},0,false},{{25.07,67.35},0,false},{{30.6,66.8},0,false},{{35.1,65.03},0,false},{{14.43,64.7},0,false},{{8.18,21.01},1,false},{{13.61,47.33},0,false},{{15.04,42.13},0,false},{{8.69,46.56},0,false},{{4.29,42.47},0,false},{{26.3,55.07},0,false},{{32.23,57.73},0,false},{{28.65,49.43},0,false},{{33.46,52.2},0,false},{{37.15,56.51},0,false},{{38.37,50.1},0,false},{{33.56,46.67},0,false},{{87.71,53.19},1,false},{{69.79,65.91},1,false},{{68.26,61.16},1,false},{{64.57,64.7},1,false},{{64.06,67.79},1,false},{{59.56,66.1},1,false},{{63.14,60.05},1,false},{{88.73,63.59},1,false},{{89.24,59.5},1,false},{{90.78,56.07},1,false},{{93.85,50.43},1,false},{{88.93,48.11},1,false},{{91.9,66.69},1,false},{{27.63,9.4},1,false},{{28.65,14.48},1,false},{{32.64,9.73},1,false},{{24.66,13.16},1,false},{{24.81,8.29},1,false},{{24.76,19.38},1,false},{{29.16,18.47},1,false},{{33.36,15.15},1,false},{{6.14,15.48},1,false},{{5.01,11.83},1,false},{{29.37,22.23},1,false},{{84.94,46.67},1,false},{{82.89,52.31},1,false},{{92.0,42.8},1,false},{{85.56,68.01},1,false},{{3.17,49.76},0,false},{{4.91,57.62},0,false},{{40.73,67.46},0,false},{{69.08,15.92},2,false},{{77.43,11.41},2,false},{{74.02,21.49},2,false},{{61.97,10.69},2,false},{{63.86,18.69},2,false},{{69.08,54.74},0,false},{{11.87,23.88},1,false},{{32.13,28.97},1,false}};

//------------- World2_Map --------------//

const std::vector<PVector> World2DEPOSITS = {{69,26},{71,76}};
const int World2MAP_WIDTH = 144; 
const int World2MAP_HEIGHT = 108; 
const std::string World2MAP = "EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEUUUUUUUUUUUEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEUUUUUUUUUUUUEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSUUUUUUUUUUUUSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSUUUUUUSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSUUUUSSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSUUSSSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSUUSSSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSEESSSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSEESSSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSEESSSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSEESSSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSEEEESSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSEEEEEESSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSEEETTTEEESSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSEETTTTTTTTTEESSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSEETTTTTTTTTTTEESSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSEETTTTTTTTTTTTTEESSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEWWWWWWWWWWWWSSSSSSSSSSSSSSEETTTTTTTTTTTTTTTESSSSSSSSSSSSSSSWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEWWWWWWWWWWWWSSSSSSSSSSSSSEETTTTTTTTTTTTTTTTTESSSSSSSSSSSSSSWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSEEEEEEEEEEWWWWWWWWWWWWSSSSSSSSSSSSSEETTTTTTTTTTTTTTTTTEESSSSSSSSSSSSSWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSEEEEEEEEEEEEWWWWWWWWWWSSSSSSSSSSSSSEEETTTTTTTTTTTTTTTTTEEESSSSSSSSSSSSSWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEWWWWEESSSSSSSSSSSSSEEETTTTTTTTTTTTTTTTTTTEEESSSSSSSSSSSSSEEWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSEEEEEETTTTTTTTTTTTTTTTTTTEEEEEESSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEETTTTTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWEEEEESSSSSSSEEEEEETTTTTTTTTTTTTTTTTTTEEEEEESSSSSSSEEEEEWWWWEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWSSSSSSSSSSSSEEEETTTTTTTTTTTTTTTTTEEEESSSSSSSSSSSSWWWWWWWWWWEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWSSSSSSSSSSSSEEETTTTTTTTTTTTTTTTTEEESSSSSSSSSSSSWWWWWWWWWWWWEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWSSSSSSSSSSSSSEETTTTTTTTTTTTTTTTTEESSSSSSSSSSSSSWWWWWWWWWWWWEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWSSSSSSSSSSSSSEEETTTTTTTTTTTTTTTEESSSSSSSSSSSSSSWWWWWWWWWWWWEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSEEETTTTTTTTTTTTTEEESSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSEEETTTTTTTTTTTEEESSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSEEEEETTTTTTTEEEESSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSEEEEEETEEEEEESSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSEEEEEEEEEESSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSEEEEEEESSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSEEEEESSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSEEEESSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSEEESSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSEESSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSEESSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSESSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSESSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSSESSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSEEESSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSEUUSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSSUUUSSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSSUUUUUSSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSSSSUUUUUUUSSSSSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEESSSSSSSSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWSSSSSSSSSSSSSSSSSEUUUUUUUUUUUESSSSSSSSSSSSSSSWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEESSSEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEUUUUUUUUUUUEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEUUUUUUUUUUUEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWWWWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEWWWWEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE";
const std::vector<Collectible> World2COLLECTIBLES = {{{25.51,78.39},0,false},{{14.04,79.4},0,false},{{40.06,95.05},0,false},{{45.2,101.58},0,true},{{32.53,88.96},0,false},{{32.14,99.85},0,false},{{53.73,95.88},0,false},{{67.24,100.53},0,false},{{61.71,103.52},0,false},{{82.89,102.19},0,false},{{52.81,104.18},0,false},{{105.46,96.55},0,false},{{109.21,91.41},0,false},{{112.71,102.02},0,false},{{92.41,100.7},0,false},{{95.02,105.01},0,false},{{131.71,83.28},0,false},{{136.37,78.19},0,false},{{138.58,89.18},0,false},{{126.43,75.16},0,false},{{123.79,89.28},0,false},{{127.11,101.86},0,false},{{132.82,97.63},0,false},{{108.69,82.61},0,false},{{118.2,84.27},0,false},{{26.71,10.78},1,false},{{24.77,5.03},1,false},{{29.32,18.24},1,false},{{5.21,8.46},1,false},{{6.14,35.5},1,false},{{31.62,11.94},1,false},{{52.61,5.03},1,false},{{49.49,15.64},1,false},{{38.83,6.85},1,false},{{38.98,16.98},1,false},{{72.46,9.12},1,false},{{76.63,3.7},1,false},{{79.94,13.92},1,false},{{66.26,3.84},1,false},{{62.78,15.26},1,false},{{105.31,8.79},1,false},{{111.36,16.47},1,false},{{99.26,15.03},1,false},{{123.27,10.61},1,false},{{128.95,9.45},1,false},{{88.88,4.14},1,false},{{95.18,8.12},1,false},{{118.95,15.03},1,false},{{117.28,9.62},1,false},{{105.92,15.92},1,false},{{130.02,23.88},1,false},{{136.32,6.96},1,false},{{111.47,16.48},1,false},{{3.53,15.26},1,false},{{15.65,45.29},2,false},{{20.69,39.29},2,false},{{23.96,51.43},2,false},{{10.66,37.94},2,false},{{11.29,50.52},2,false},{{129.26,59.39},2,false},{{131.71,44.95},2,false},{{136.89,65.24},2,false},{{125.27,51.8},2,false},{{123.74,63.47},2,false},{{26.25,61.05},2,false},{{31.62,55.05},2,false},{{31.19,68.92},2,false},{{19.0,56.58},2,false},{{114.67,54.41},2,false},{{122.35,35.99},2,false},{{126.57,31.77},2,false},{{136.01,54.91},2,false},{{117.98,30.23},2,false},{{115.44,42.04},2,false},{{116.98,71.0},2,false},{{116.05,64.86},2,false},{{121.06,79.21},2,false},{{109.06,77.19},2,false},{{110.37,49.93},2,false},{{108.38,32.68},2,false},{{108.38,63.87},2,false},{{106.05,44.07},2,false},{{104.9,54.3},2,false},{{30.08,35.17},2,false},{{32.69,41.64},2,false},{{28.7,26.04},2,false},{{27.78,45.45},2,false},{{113.6,26.54},1,false},{{6.44,83.44},1,false},{{23.02,33.01},1,false}};


