.TH "Area" 3 "Mon Apr 5 2021" "Extraterrestrial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Area
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MapData\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArea\fP (const std::vector< \fBPVector\fP > &p_s)"
.br
.ti -1c
.RI "const std::vector< \fBPVector\fP > & \fBgetCorners\fP () const"
.br
.RI "Getter method for Area::Corners_\&. "
.ti -1c
.RI "const std::vector< \fBLine\fP > & \fBgetEdges\fP () const"
.br
.RI "Getter method for Area::Edges_\&. "
.ti -1c
.RI "const \fBPVector\fP & \fBgetMin\fP () const"
.br
.RI "Getter method for Area::min_\&. "
.ti -1c
.RI "const \fBPVector\fP & \fBgetMax\fP () const"
.br
.RI "Getter method for Area::max_\&. "
.in -1c
.SH "Detailed Description"
.PP 
A polygon in a 2D grid
.PP
The area is defined by a collection of points (also known as polygons)\&. The points have to be stored in a specific order to prevent mistakes\&. The edge a is defined by line(p_s[i], p_s[i+1]) with the only exception being the last element of p that is connected with the first one
.PP
\fBTemplate Parameters\fP
.RS 4
\fIp_s\fP The Corners of the \fBArea\fP 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Area::Area (const std::vector< \fBPVector\fP > & p_s)\fC [explicit]\fP"

.PP
 \fBArea\fP 
.br
 
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "const std::vector< \fBPVector\fP > & Area::getCorners () const"

.PP
Getter method for Area::Corners_\&. 
.SS "const std::vector< \fBLine\fP > & Area::getEdges () const"

.PP
Getter method for Area::Edges_\&. 
.SS "const \fBPVector\fP & Area::getMax () const"

.PP
Getter method for Area::max_\&. 
.SS "const \fBPVector\fP & Area::getMin () const"

.PP
Getter method for Area::min_\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Extraterrestrial from the source code\&.
