.TH "code/libs/ColorRecognition.cpp" 3 "Mon Apr 5 2021" "Extraterrestrial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/libs/ColorRecognition.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'ColorRecognition\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBisRed\fP (\fBHSLColor\fP c)"
.br
.ti -1c
.RI "bool \fBisCyan\fP (\fBHSLColor\fP c)"
.br
.ti -1c
.RI "bool \fBisBlack\fP (\fBHSLColor\fP c)"
.br
.ti -1c
.RI "bool \fBisYellow\fP (\fBHSLColor\fP c)"
.br
.ti -1c
.RI "bool \fBisOrange\fP (\fBHSLColor\fP c)"
.br
.ti -1c
.RI "bool \fBisSwamp\fP (\fBHSLColor\fP c)"
.br
.ti -1c
.RI "bool \fBisSuperObj\fP (\fBHSLColor\fP c)"
.br
.ti -1c
.RI "bool \fBisColor\fP (\fBHSLColor\fP c)"
.br
.ti -1c
.RI "float \fBrgb2h\fP (\fBRGBColor\fP c)"
.br
.ti -1c
.RI "float \fBrgb2s\fP (\fBRGBColor\fP c)"
.br
.ti -1c
.RI "float \fBrgb2l\fP (\fBRGBColor\fP c)"
.br
.ti -1c
.RI "\fBHSLColor\fP \fBrgb2hsl\fP (\fBRGBColor\fP rgb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool isBlack (\fBHSLColor\fP c)"

.SS "bool isColor (\fBHSLColor\fP c)"

.SS "bool isCyan (\fBHSLColor\fP c)"

.SS "bool isOrange (\fBHSLColor\fP c)"

.SS "bool isRed (\fBHSLColor\fP c)"

.SS "bool isSuperObj (\fBHSLColor\fP c)"

.SS "bool isSwamp (\fBHSLColor\fP c)"

.SS "bool isYellow (\fBHSLColor\fP c)"

.SS "float rgb2h (\fBRGBColor\fP c)"

.SS "\fBHSLColor\fP rgb2hsl (\fBRGBColor\fP rgb)"

.SS "float rgb2l (\fBRGBColor\fP c)"

.SS "float rgb2s (\fBRGBColor\fP c)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Extraterrestrial from the source code\&.
