.TH "code/libs/CommonFunctions.hpp" 3 "Mon Apr 5 2021" "Extraterrestrial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/libs/CommonFunctions.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cmath>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBtoRadians\fP (double n)"
.br
.ti -1c
.RI "double \fBtoDegrees\fP (double n)"
.br
.ti -1c
.RI "double \fBreverseAngle\fP (double angle)"
.br
.ti -1c
.RI "bool \fBisInRange\fP (double value, double min, double max)"
.br
.ti -1c
.RI "double \fBmap\fP (double Mmin, double Mmax, double Imin, double Imax, double input)"
.br
.ti -1c
.RI "template<class T1 , class T2 > std::string \fBstr\fP (T1 x, T2 y)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool isInRange (double value, double min, double max)"

.SS "double map (double Mmin, double Mmax, double Imin, double Imax, double input)"

.SS "double reverseAngle (double angle)"

.SS "template<class T1 , class T2 > std::string str (T1 x, T2 y)"

.SS "double toDegrees (double n)"

.SS "double toRadians (double n)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Extraterrestrial from the source code\&.
