.TH "code/libs/CoSpaceFunctions.cpp" 3 "Mon Apr 5 2021" "Extraterrestrial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/libs/CoSpaceFunctions.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CoSpaceFunctions\&.hpp'\fP
.br
\fC#include 'CommonFunctions\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDLL_EXPORT\fP void \fBSetGameID\fP (int GameID)"
.br
.ti -1c
.RI "\fBDLL_EXPORT\fP int \fBGetGameID\fP ()"
.br
.ti -1c
.RI "\fBDLL_EXPORT\fP int \fBIsGameEnd\fP ()"
.br
.ti -1c
.RI "\fBDLL_EXPORT\fP char * \fBGetDebugInfo\fP ()"
.br
.ti -1c
.RI "\fBDLL_EXPORT\fP char * \fBGetTeamName\fP ()"
.br
.ti -1c
.RI "\fBDLL_EXPORT\fP int \fBGetCurAction\fP ()"
.br
.ti -1c
.RI "\fBDLL_EXPORT\fP int \fBGetTeleport\fP ()"
.br
.ti -1c
.RI "\fBDLL_EXPORT\fP void \fBSetSuperObj\fP (int X, int Y, int num)"
.br
.ti -1c
.RI "\fBDLL_EXPORT\fP void \fBGetSuperObj\fP (int *X, int *Y, int *num)"
.br
.ti -1c
.RI "\fBDLL_EXPORT\fP void \fBSetDataAI\fP (volatile int *packet, volatile int *AI_IN)"
.br
.ti -1c
.RI "\fBDLL_EXPORT\fP void \fBGetCommand\fP (int *AI_OUT)"
.br
.ti -1c
.RI "\fBDLL_EXPORT\fP void \fBOnTimer\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "volatile int * \fBINPUT\fP = nullptr"
.br
.ti -1c
.RI "volatile int * \fBOUTPUT\fP = nullptr"
.br
.ti -1c
.RI "char \fBAI_MyID\fP [2] = {'0', '2'}"
.br
.ti -1c
.RI "int \fBDuration\fP = 0"
.br
.ti -1c
.RI "int \fBSuperDuration\fP = 0"
.br
.ti -1c
.RI "int \fBbGameEnd\fP = false"
.br
.ti -1c
.RI "int \fBCurAction\fP = \-1"
.br
.ti -1c
.RI "int \fBCurGame\fP = 0"
.br
.ti -1c
.RI "int \fBSuperObj_Num\fP = 0"
.br
.ti -1c
.RI "int \fBSuperObj_X\fP = 0"
.br
.ti -1c
.RI "int \fBSuperObj_Y\fP = 0"
.br
.ti -1c
.RI "int \fBTeleport\fP = 0"
.br
.ti -1c
.RI "int \fBLoadedObjects\fP = 0"
.br
.ti -1c
.RI "int \fBUS_Front\fP = 0"
.br
.ti -1c
.RI "int \fBUS_Left\fP = 0"
.br
.ti -1c
.RI "int \fBUS_Right\fP = 0"
.br
.ti -1c
.RI "int \fBCSLeft_R\fP = 0"
.br
.ti -1c
.RI "int \fBCSLeft_G\fP = 0"
.br
.ti -1c
.RI "int \fBCSLeft_B\fP = 0"
.br
.ti -1c
.RI "int \fBCSRight_R\fP = 0"
.br
.ti -1c
.RI "int \fBCSRight_G\fP = 0"
.br
.ti -1c
.RI "int \fBCSRight_B\fP = 0"
.br
.ti -1c
.RI "int \fBPositionX\fP = 0"
.br
.ti -1c
.RI "int \fBPositionY\fP = 0"
.br
.ti -1c
.RI "int \fBTM_State\fP = 0"
.br
.ti -1c
.RI "int \fBCompass\fP = 0"
.br
.ti -1c
.RI "int \fBTime\fP = 0"
.br
.ti -1c
.RI "int \fBWheelLeft\fP = 0"
.br
.ti -1c
.RI "int \fBWheelRight\fP = 0"
.br
.ti -1c
.RI "int \fBLED_1\fP = 0"
.br
.ti -1c
.RI "int \fBMyState\fP = 0"
.br
.ti -1c
.RI "unsigned int \fBcycle\fP = 0"
.br
.ti -1c
.RI "int \fBAI_SensorNum\fP = 13"
.br
.ti -1c
.RI "int \fBOtherRob_PositionX\fP"
.br
.ti -1c
.RI "int \fBOtherRob_PositionY\fP"
.br
.ti -1c
.RI "int \fBObjState\fP"
.br
.ti -1c
.RI "int \fBObjPositionX\fP"
.br
.ti -1c
.RI "int \fBObjPositionY\fP"
.br
.ti -1c
.RI "int \fBObjDuration\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBDLL_EXPORT\fP void GetCommand (int * AI_OUT)"

.SS "\fBDLL_EXPORT\fP int GetCurAction ()"

.SS "\fBDLL_EXPORT\fP char* GetDebugInfo ()"

.SS "\fBDLL_EXPORT\fP int GetGameID ()"

.SS "\fBDLL_EXPORT\fP void GetSuperObj (int * X, int * Y, int * num)"

.SS "\fBDLL_EXPORT\fP char* GetTeamName ()"

.SS "\fBDLL_EXPORT\fP int GetTeleport ()"

.SS "\fBDLL_EXPORT\fP int IsGameEnd ()"

.SS "\fBDLL_EXPORT\fP void OnTimer ()"

.SS "\fBDLL_EXPORT\fP void SetDataAI (volatile int * packet, volatile int * AI_IN)"

.SS "\fBDLL_EXPORT\fP void SetGameID (int GameID)"

.SS "\fBDLL_EXPORT\fP void SetSuperObj (int X, int Y, int num)"

.SH "Variable Documentation"
.PP 
.SS "char AI_MyID[2] = {'0', '2'}"

.SS "int AI_SensorNum = 13"

.SS "int bGameEnd = false"

.SS "int Compass = 0"

.SS "int CSLeft_B = 0"

.SS "int CSLeft_G = 0"

.SS "int CSLeft_R = 0"

.SS "int CSRight_B = 0"

.SS "int CSRight_G = 0"

.SS "int CSRight_R = 0"

.SS "int CurAction = \-1"

.SS "int CurGame = 0"

.SS "unsigned int cycle = 0"

.SS "int Duration = 0"

.SS "volatile int* INPUT = nullptr"

.SS "int LED_1 = 0"

.SS "int LoadedObjects = 0"

.SS "int MyState = 0"

.SS "int ObjDuration"

.SS "int ObjPositionX"

.SS "int ObjPositionY"

.SS "int ObjState"

.SS "int OtherRob_PositionX"

.SS "int OtherRob_PositionY"

.SS "volatile int* OUTPUT = nullptr"

.SS "int PositionX = 0"

.SS "int PositionY = 0"

.SS "int SuperDuration = 0"

.SS "int SuperObj_Num = 0"

.SS "int SuperObj_X = 0"

.SS "int SuperObj_Y = 0"

.SS "int Teleport = 0"

.SS "int Time = 0"

.SS "int TM_State = 0"

.SS "int US_Front = 0"

.SS "int US_Left = 0"

.SS "int US_Right = 0"

.SS "int WheelLeft = 0"

.SS "int WheelRight = 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for Extraterrestrial from the source code\&.
