.TH "Field" 3 "Mon Apr 5 2021" "Extraterrestrial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Field
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MapData\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBField\fP (const int &width, const int &height, const std::vector< \fBArea\fP > &walls, const std::vector< \fBArea\fP > &traps, const std::vector< \fBArea\fP > &swamps, const std::vector< \fBArea\fP > &waters, const std::vector< \fBPVector\fP > &deposits, const std::vector< \fBPVector\fP > &wallNodes, const std::vector< \fBPVector\fP > &trapNodes, const std::vector< \fBPVector\fP > &swampNodes, const std::vector< \fBCollectible\fP > &collectibles)"
.br
.ti -1c
.RI "\fBCollectible\fP * \fBaddCollectible\fP (\fBCollectible\fP collectible)"
.br
.ti -1c
.RI "bool \fBremoveCollectible\fP (\fBCollectible\fP collectible)"
.br
.ti -1c
.RI "\fBCollectible\fP * \fBgetCollectible\fP (\fBPVector\fP pos, double angle, double uncertainty, int color)"
.br
.ti -1c
.RI "\fBPVector\fP \fBgetSize\fP ()"
.br
.RI "Getter for the size\&. "
.ti -1c
.RI "std::vector< \fBArea\fP > \fBgetMapObjects\fP (const std::vector< unsigned int > &indices)"
.br
.ti -1c
.RI "std::vector< \fBPVector\fP > \fBgetMapNodes\fP (const std::vector< unsigned int > &indices)"
.br
.ti -1c
.RI "std::vector< \fBPVector\fP > \fBgetDeposits\fP ()"
.br
.RI "Getter method for deposits\&. "
.ti -1c
.RI "std::vector< \fBCollectible\fP > \fBgetCollectibles\fP (const std::vector< unsigned int > &colors)"
.br
.RI "Getter method for collectibles\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains all important map data about the map
.PP
It contains all information given by the map_interpreter\&.py script\&. This information is enough to fully reconstruct the map from one field-object
.PP
\fBTemplate Parameters\fP
.RS 4
\fIwidth\fP width of the map 
.br
\fIheight\fP height of the map 
.br
\fIwalls\fP All walls 
.br
\fItraps\fP All traps 
.br
\fIswamps\fP All swamps 
.br
\fIwaters\fP All waters/bonus areas 
.br
\fIdeposits\fP All deposits 
.br
\fIcollectibles\fP All collectibles
.RE
.PP
TODO: show function for \fBField\fP class\&. (for Debugging) 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Field::Field (const int & width, const int & height, const std::vector< \fBArea\fP > & walls, const std::vector< \fBArea\fP > & traps, const std::vector< \fBArea\fP > & swamps, const std::vector< \fBArea\fP > & waters, const std::vector< \fBPVector\fP > & deposits, const std::vector< \fBPVector\fP > & wallNodes, const std::vector< \fBPVector\fP > & trapNodes, const std::vector< \fBPVector\fP > & swampNodes, const std::vector< \fBCollectible\fP > & collectibles)"

.PP
 MapData 
.br
 
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "\fBCollectible\fP * Field::addCollectible (\fBCollectible\fP collectible)"

.SS "\fBCollectible\fP * Field::getCollectible (\fBPVector\fP pos, double angle, double uncertainty, int color)"

.SS "std::vector< \fBCollectible\fP > Field::getCollectibles (const std::vector< unsigned int > & colors)"

.PP
Getter method for collectibles\&. Getter for field::collectibles 
.SS "std::vector< \fBPVector\fP > Field::getDeposits ()"

.PP
Getter method for deposits\&. Getter for field::collectibles 
.SS "std::vector< \fBPVector\fP > Field::getMapNodes (const std::vector< unsigned int > & indices)"
gets map nodes based on their index
.PP
\fBParameters\fP
.RS 4
\fIindices\fP 0 -> walls; 1 -> traps; 2 -> swamps
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing all map object areas with the indices 
.RE
.PP

.SS "std::vector< \fBArea\fP > Field::getMapObjects (const std::vector< unsigned int > & indices)"
gets map objects based on their index
.PP
\fBParameters\fP
.RS 4
\fIindices\fP the index of the wanted map objects 0 -> walls; 1 -> traps; 2 -> swamps; 3 -> bonus areas;
.RE
.PP
\fBReturns\fP
.RS 4
a vector containing all map object areas with the indices 
.RE
.PP

.SS "\fBPVector\fP Field::getSize ()"

.PP
Getter for the size\&. 
.SS "bool Field::removeCollectible (\fBCollectible\fP collectible)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Extraterrestrial from the source code\&.
