.TH "HSLColor" 3 "Mon Apr 5 2021" "Extraterrestrial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HSLColor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ColorRecognition\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBh\fP = 0"
.br
.ti -1c
.RI "float \fBs\fP = 0"
.br
.ti -1c
.RI "float \fBl\fP = 0"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "float HSLColor::h = 0"

.SS "float HSLColor::l = 0"

.SS "float HSLColor::s = 0"


.SH "Author"
.PP 
Generated automatically by Doxygen for Extraterrestrial from the source code\&.
