.TH "code/main.cpp" 3 "Mon Apr 5 2021" "Extraterrestrial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'libs/PPSettings\&.hpp'\fP
.br
\fC#include 'libs/CoSpaceFunctions\&.hpp'\fP
.br
\fC#include 'libs/CommonFunctions\&.hpp'\fP
.br
\fC#include 'libs/ColorRecognition\&.hpp'\fP
.br
\fC#include 'Pathfinder\&.hpp'\fP
.br
\fC#include 'MapData\&.hpp'\fP
.br
\fC#include 'Robot\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fileapi\&.h>\fP
.br
\fC#include 'SFMLWindow\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCsBot_AI_H\fP"
.br
.ti -1c
.RI "#define \fBCsBot_AI_C\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSetup\fP ()"
.br
.ti -1c
.RI "void \fBGame0\fP ()"
.br
.ti -1c
.RI "void \fBGame1\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBDebugWindow\fP * \fBdebugWindow\fP = nullptr"
.br
.ti -1c
.RI "\fBField\fP * \fBGAME0\fP = nullptr"
.br
.ti -1c
.RI "\fBField\fP * \fBGAME1\fP = nullptr"
.br
.ti -1c
.RI "\fBRobot\fP * \fBBot\fP = nullptr"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CsBot_AI_C"

.SS "#define CsBot_AI_H"

.SH "Function Documentation"
.PP 
.SS "void Game0 ()"

.SS "void Game1 ()"

.SS "void Setup ()"

.SH "Variable Documentation"
.PP 
.SS "\fBRobot\fP* Bot = nullptr"

.SS "\fBDebugWindow\fP* debugWindow = nullptr"

.SS "\fBField\fP* GAME0 = nullptr"

.SS "\fBField\fP* GAME1 = nullptr"

.SH "Author"
.PP 
Generated automatically by Doxygen for Extraterrestrial from the source code\&.
