.TH "code/MapData.cpp" 3 "Mon Apr 5 2021" "Extraterrestrial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/MapData.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <algorithm>\fP
.br
\fC#include 'MapData\&.hpp'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const std::vector< \fBArea\fP > \fBGAME0WALLS\fP"
.br
.ti -1c
.RI "const std::vector< \fBArea\fP > \fBGAME0TRAPS\fP"
.br
.ti -1c
.RI "const std::vector< \fBArea\fP > \fBGAME0SWAMPS\fP = {}"
.br
.ti -1c
.RI "const std::vector< \fBArea\fP > \fBGAME0WATERS\fP"
.br
.ti -1c
.RI "const std::vector< \fBPVector\fP > \fBGAME0DEPOSITS\fP"
.br
.ti -1c
.RI "const std::vector< \fBPVector\fP > \fBGAME0WALLNODES\fP"
.br
.ti -1c
.RI "const std::vector< \fBPVector\fP > \fBGAME0TRAPNODES\fP"
.br
.ti -1c
.RI "const std::vector< \fBPVector\fP > \fBGAME0SWAMPNODES\fP = {}"
.br
.ti -1c
.RI "const std::vector< \fBCollectible\fP > \fBGAME0COLLECTIBLES\fP"
.br
.ti -1c
.RI "const std::vector< \fBArea\fP > \fBGAME1WALLS\fP = {}"
.br
.ti -1c
.RI "const std::vector< \fBArea\fP > \fBGAME1TRAPS\fP"
.br
.ti -1c
.RI "const std::vector< \fBArea\fP > \fBGAME1SWAMPS\fP"
.br
.ti -1c
.RI "const std::vector< \fBArea\fP > \fBGAME1WATERS\fP"
.br
.ti -1c
.RI "const std::vector< \fBPVector\fP > \fBGAME1DEPOSITS\fP"
.br
.ti -1c
.RI "const std::vector< \fBPVector\fP > \fBGAME1WALLNODES\fP = {}"
.br
.ti -1c
.RI "const std::vector< \fBPVector\fP > \fBGAME1TRAPNODES\fP"
.br
.ti -1c
.RI "const std::vector< \fBPVector\fP > \fBGAME1SWAMPNODES\fP"
.br
.ti -1c
.RI "const std::vector< \fBCollectible\fP > \fBGAME1COLLECTIBLES\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const std::vector<\fBCollectible\fP> GAME0COLLECTIBLES"

.SS "const std::vector<\fBPVector\fP> GAME0DEPOSITS"
\fBInitial value:\fP
.PP
.nf
= {{197, 27},
                                            {38,  147}}
.fi
.SS "const std::vector<\fBPVector\fP> GAME0SWAMPNODES = {}"

.SS "const std::vector<\fBArea\fP> GAME0SWAMPS = {}"

.SS "const std::vector<\fBPVector\fP> GAME0TRAPNODES"
\fBInitial value:\fP
.PP
.nf
= {{104, 116},
                                             {139, 116},
                                             {139, 82},
                                             {104, 82}}
.fi
.SS "const std::vector<\fBArea\fP> GAME0TRAPS"
\fBInitial value:\fP
.PP
.nf
= {
        Area({{105, 115},
              {138, 115},
              {138, 83},
              {105, 83}})}
.fi
.SS "const std::vector<\fBPVector\fP> GAME0WALLNODES"
\fBInitial value:\fP
.PP
.nf
= {{87,  167},
                                             {157, 167},
                                             {157, 142},
                                             {87,  142},
                                             {44,  131},
                                             {69,  131},
                                             {69,  61},
                                             {44,  61},
                                             {188, 131},
                                             {212, 131},
                                             {212, 61},
                                             {188, 61},
                                             {90,  34},
                                             {159, 34},
                                             {159, 10},
                                             {90,  10}}
.fi
.SS "const std::vector<\fBArea\fP> GAME0WALLS"
\fBInitial value:\fP
.PP
.nf
= {
        Area({{88,  166},
              {156, 166},
              {156, 143},
              {88,  143}}),
        Area({{45, 130},
              {68, 130},
              {68, 62},
              {45, 62}}),
        Area({{189, 130},
              {211, 130},
              {211, 62},
              {189, 62}}),
        Area({{91,  33},
              {158, 33},
              {158, 11},
              {91,  11}})}
.fi

.PP
 | | |\&.---\&.-\&.\&.-----\&.| \\ \&.---\&.-\&.| |_ \&.---\&.-\&. | || _ || _ || -- || _ || _|| _ | |__|_|__||___\&._|| __||_____/ |___\&._||____||___\&._| |__| 
.SS "const std::vector<\fBArea\fP> GAME0WATERS"

.SS "const std::vector<\fBCollectible\fP> GAME1COLLECTIBLES"

.SS "const std::vector<\fBPVector\fP> GAME1DEPOSITS"
\fBInitial value:\fP
.PP
.nf
= {{174, 64},
                                            {177, 197}}
.fi
.SS "const std::vector<\fBPVector\fP> GAME1SWAMPNODES"

.SS "const std::vector<\fBArea\fP> GAME1SWAMPS"

.SS "const std::vector<\fBPVector\fP> GAME1TRAPNODES"

.SS "const std::vector<\fBArea\fP> GAME1TRAPS"

.SS "const std::vector<\fBPVector\fP> GAME1WALLNODES = {}"

.SS "const std::vector<\fBArea\fP> GAME1WALLS = {}"

.SS "const std::vector<\fBArea\fP> GAME1WATERS"

.SH "Author"
.PP 
Generated automatically by Doxygen for Extraterrestrial from the source code\&.
