.TH "ObjectLoad" 3 "Mon Apr 5 2021" "Extraterrestrial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectLoad
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Robot\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObjectLoad\fP ()"
.br
.ti -1c
.RI "\fBObjectLoad\fP (const std::vector< \fBCollectible\fP * > &collectibles)"
.br
.ti -1c
.RI "void \fBaddObject\fP (\fBCollectible\fP *collectible)"
.br
.ti -1c
.RI "bool \fBremoveObject\fP (\fBCollectible\fP *collectible)"
.br
.ti -1c
.RI "void \fBsetLoad\fP (const std::vector< \fBCollectible\fP * > &collectible)"
.br
.ti -1c
.RI "void \fBclearLoad\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetValue\fP ()"
.br
.ti -1c
.RI "unsigned int \fBrgb\fP ()"
.br
.ti -1c
.RI "unsigned int \fBred\fP ()"
.br
.ti -1c
.RI "unsigned int \fBcyan\fP ()"
.br
.ti -1c
.RI "unsigned int \fBblack\fP ()"
.br
.ti -1c
.RI "unsigned int \fBsuper\fP ()"
.br
.ti -1c
.RI "std::array< unsigned int, 4 > \fBall\fP ()"
.br
.ti -1c
.RI "const std::array< std::vector< \fBCollectible\fP * >, 4 > & \fBloadedObjects\fP ()"
.br
.ti -1c
.RI "unsigned int \fBnum\fP () const"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ObjectLoad::ObjectLoad ()"

.SS "ObjectLoad::ObjectLoad (const std::vector< \fBCollectible\fP * > & collectibles)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ObjectLoad::addObject (\fBCollectible\fP * collectible)"

.SS "std::array< unsigned int, 4 > ObjectLoad::all ()"

.SS "unsigned int ObjectLoad::black ()"

.SS "void ObjectLoad::clearLoad ()"

.SS "unsigned int ObjectLoad::cyan ()"

.SS "unsigned int ObjectLoad::getValue ()"

.SS "const std::array< std::vector< \fBCollectible\fP * >, 4 > & ObjectLoad::loadedObjects ()"

.SS "unsigned int ObjectLoad::num () const"

.SS "unsigned int ObjectLoad::red ()"

.SS "bool ObjectLoad::removeObject (\fBCollectible\fP * collectible)"

.SS "unsigned int ObjectLoad::rgb ()"

.SS "void ObjectLoad::setLoad (const std::vector< \fBCollectible\fP * > & collectible)"

.SS "unsigned int ObjectLoad::super ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Extraterrestrial from the source code\&.
