.TH "code/Robot.hpp" 3 "Mon Apr 5 2021" "Extraterrestrial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/Robot.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'libs/PPSettings\&.hpp'\fP
.br
\fC#include 'libs/CommonFunctions\&.hpp'\fP
.br
\fC#include 'libs/ColorRecognition\&.hpp'\fP
.br
\fC#include 'libs/CoSpaceFunctions\&.hpp'\fP
.br
\fC#include 'MapData\&.hpp'\fP
.br
\fC#include 'Pathfinder\&.hpp'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <ctime>\fP
.br
\fC#include <chrono>\fP
.br
\fC#include <array>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBObjectLoad\fP"
.br
.ti -1c
.RI "class \fBRobot\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Extraterrestrial from the source code\&.
