.TH "code/SFMLWindow.hpp" 3 "Mon Apr 5 2021" "Extraterrestrial" \" -*- nroff -*-
.ad l
.nh
.SH NAME
code/SFMLWindow.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <SFML/Graphics\&.hpp>\fP
.br
\fC#include 'Robot\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDebugWindow\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Extraterrestrial from the source code\&.
